doctrine_migrations:
    migrations_paths:
        'DoctrineMigrations': 'src/Migrations'

    services:
        'Doctrine\Migrations\Version\MigrationFactory': 'App\Migrations\Factory\MigrationFactoryDecorator'

    storage:
        table_storage:
            table_name: 'migration_versions'
