framework:
    default_locale: '%app.locale%'
    translator:
        default_path: '%kernel.project_dir%/config/translations'
        fallbacks:
            - '%app.locale%'
        paths:
            - '%kernel.project_dir%/translations'
