twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_4_layout.html.twig']
    globals:
        build_tag: '%env(IMAGE_BUILD_TAG)%'
        slot_interval: '%app.slot_interval%'
