imports:
    - { resource: ../dev/* }

framework:
    session:
        storage_id: session.storage.native
        handler_id: Symfony\Component\HttpFoundation\Session\Storage\Handler\PdoSessionHandler
    profiler: { collect: false }
