_organizations:
    resource: ../src/Controller/Organization/
    type: annotation
    prefix: /organizations

_organizations_planning:
    resource: ../src/Controller/Organization/Planning
    type: annotation
    prefix: /organizations/planning
