services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Tests\Behat\:
        resource: '../tests/Behat/*'

    Symfony\Component\BrowserKit\CookieJar: '@test.client.cookiejar'
