services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Tests\Behat\:
        resource: '../tests/Behat/*'

    App\Tests\Behat\FixturesContext:
        arguments:
            $aliceFixturesLoader: '@hautelook_alice.loader'

    App\Tests\Behat\TraversingContext:
        arguments:
            $projectDir: '%kernel.project_dir%'

    App\Tests\Behat\UserPlanningContext:
        arguments:
            $slotInterval: '%app.slot_interval%'
