services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Tests\Behat\:
        resource: '../tests/Behat/*'

    App\Tests\Behat\FixturesContext:
        $aliceFixturesLoader: '@hautelook_alice.loader'

    App\Tests\Behat\TraversingContext:
        $projectDir: '%kernel.project_dir%'
