services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Tests\Behat\:
        resource: '../tests/Behat/*'

    App\Tests\Behat\FixturesContext:
        arguments:
            $loader: '@fidry_alice_data_fixtures.loader.doctrine'
