# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    app.most_important_skills_limit: 6 # used for separing data in the planning
    app.most_important_skills_to_display: 3 # used for displaying a badge near the user name
    app.slot_interval: '%env(APP_SLOT_INTERVAL)%'
    app.available_skills:
        # Caution: the order matters for the planning display
        ci_bspp:
            label: CI Réseau BSPP
            includes: [ci_samu]
        ci_samu:
            label: CI Réseau Samu
            includes: [ci]
        ch_vpsp:
            label: Chauffeur VPSP
            includes: [pse2, ch_vl]
        ci:
            label: CI
            includes: [pse2]
        pse2:
            label: PSE2
            includes: [pse1]
        pse1:
            label: PSE1
            includes: [psc1]
        ch_vl:
            label: Chauffeur VL
            includes: [benevole]
        infirmier:
            label: Infirmier.e local.e
            includes: [benevole]
        ce_maraude:
            label: Chef.fe d'équipe maraudes
            includes: [solidar]
        solidar:
            label: Solidar
            includes: [maraudeur]
        maraudeur:
            label: Maraudeur.se
            includes: [benevole]
        tsa_coreg:
            label: TSA / Coreg
            includes: [pse2]
        logisticien:
            label: Logisticien.ne Croix-Rouge
            includes: [benevole]
        resp_perm_soc:
            label: Responsable Permanence Sociale
            includes: [benevole]
        anim_fle:
            label: Animateur.rice de cours de FLE
            includes: [benevole]
        psc1:
            label: PSC1
            includes: [benevole]
        benevole:
            label: Bénévole

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            $isDebug: '%kernel.debug%'
            $availableSkillSets: "%app.available_skills%"
            $importantSkillsLimit: "%app.most_important_skills_limit%"
            $importantSkillsToDisplayLimit: "%app.most_important_skills_to_display%"
            $slotInterval: '%app.slot_interval%'

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: "../src/*"
        exclude: "../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}"

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: "../src/Controller"
        tags: ["controller.service_arguments"]
    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    App\EntityListener\:
        resource: "../src/EntityListener"
        tags: ["doctrine.orm.entity_listener"]

    App\DataFixtures\ApplicationFixtures:
        arguments:
            $nbUsers: '%env(int:APP_NB_USERS)%'
            $nbAvailabilities: '%env(int:APP_NB_AVAILABILITIES)%'

    App\DataFixtures\Faker\Provider\:
        resource: '../src/DataFixtures/Faker/Provider'
        tags: ['nelmio_alice.faker.provider']

    App\DataFixtures\Factory\:
        resource: '../src/DataFixtures/Factory'
        public: true # Required by fixtures

    Symfony\Component\HttpFoundation\Session\Storage\Handler\PdoSessionHandler:
        arguments:
             - !service { class: PDO, factory: ['@database_connection', 'getWrappedConnection'] }
            # If you get transaction issues (e.g. after login) uncomment the line below
             - { lock_mode: 1 }

    # twig/cache-extension
    Twig\CacheExtension\CacheProvider\PsrCacheAdapter:
        arguments:
            $cache: '@cache.twig'
    Twig\CacheExtension\CacheStrategy\GenerationalCacheStrategy:
        arguments:
            $cache: '@Twig\CacheExtension\CacheProvider\PsrCacheAdapter'
            $keyGenerator: '@App\Twig\Cache\RequestGenerator'
            $lifetime: 86400 # 1 day

    # The cache strategy is overrided in services_dev
    Twig\CacheExtension\CacheStrategyInterface: '@Twig\CacheExtension\CacheStrategy\GenerationalCacheStrategy'
    Twig\CacheExtension\Extension:
        arguments:
            $cacheStrategy: '@Twig\CacheExtension\CacheStrategyInterface'

    # declared as public because needed in a migration
    App\Domain\SkillSetDomain:
        public: true

    datetime_normalizer:
        class: Symfony\Component\Serializer\Normalizer\DateTimeNormalizer
        tags: [serializer.normalizer]
